### ISSUE TITLE
Uncaught RangeError: The value of "offset" is out of range.

### ISSUE THREAD

**Issue by UziTech** [princjef/font-finder#7]
When running `fontFinder.list()` this error happens for some users.

```
// x is a number that seems to change depending on the user.

Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= x. Received x+2

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= x. Received x+2
    at boundsError (internal/buffer.js:73:9)
    at Buffer.readInt16BE (internal/buffer.js:493:5)
    at /packages/x-terminal/node_modules/font-finder/dist/tables/os2.js:56:29)
    at /packages/x-terminal/node_modules/font-finder/dist/parse.js:95:65
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

ref https://github.com/xtermjs/xterm.js/issues/3174

related https://github.com/bus-stop/x-terminal/issues/204
related https://github.com/bus-stop/x-terminal/issues/206
related https://github.com/bus-stop/x-terminal/issues/211

See [this youtube video](https://www.youtube.com/watch?v=d0gx5FX1064)

I am not able to reproduce it but a few others have been. After lots of debugging it seems to be when certain fonts are installed on the system (although we are not sure which ones).

**Comment by UziTech** [comment]
https://github.com/bus-stop/x-terminal/issues/204#issuecomment-725613349

Here is more information about the error.

I'm not sure what the fix should be but maybe somehow just quiet the errors when loading fonts?

**Comment by UziTech** [comment]
I have confirmed that having a way to quiet the errors would still allow it to work the way it is supposed to.

Maybe an option that quiets the errors? Maybe something like: `fontFinder.list({quiet: true})`

**Comment by UziTech** [comment]
@princjef any feedback?

**Comment by princjef** [comment]
Hey @UziTech sorry for the delay. I agree that it's probably a good idea to provide a way to suppress individual font errors to avoid these kinds of problems.

Knowing which font causes it would be great, but absent that this seems like the best way forward

**Comment by UziTech** [comment]
Or maybe just an error message that shows which font threw the error

**Comment by princjef** [comment]
Sounds reasonable

**Comment by princjef** [comment]
I've done a little more digging on the code side here and it looks like the issue is probably related to differences between the OpenType spec and Apple's own font guidelines.

The error looks to be coming out of the OS/2 table, which is a particular pain point between the two (the spec requires it, Apple omits it). Having a `quiet` option is fine for the general case, but it has the impact of discarding potentially valid fonts.

In this case it looks like the OS/2 table is too short to be valid for what we're trying to parse. If the font file header itself is valid (should be even for these), that can be verified upfront and we can toss the OS/2 table if the length isn't long enough, falling back to the logic [here](https://github.com/princjef/font-finder/pull/6).

I'll work up a second PR for this case. Hopefully that will fix the specific issue here, while the `quiet` mode gives an escape hatch for the future.

**Comment by princjef** [comment]
Ahh I bet it's [this](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6OS2.html) (emphasis mine):

> The format of this table has changed over time. The original TrueType specification had this table at 68 bytes long. The first OpenType version had it at 78 bytes long, and the current OpenType version is even larger. _To determine which kind of table your software is dealing with, it's best both to consider the table's version and its size._

Regardless, the table size check I mentioned should take care of this.
